### ISSUE TITLE
how can i  implement  it in iOS APP?

### ISSUE THREAD

**Issue by jincysam** [H2CO3/libsprec#12]
can you give any example?

**Comment by H2CO3** [comment]
There's nothing special about an Xcode project which would require any special treatment. Copy/add the files to your project and you should be good to go.

**Comment by jincysam** [comment]
i can't able to download these files 
cURL 7.25.0
libogg
libflac

**Comment by H2CO3** [comment]
Specifically why?

**Comment by jincysam** [comment]
can u sent me that 3 files

**Comment by jincysam** [comment]
For iOS,  download the Debian packages from here:

cURL 7.25.0
libogg
libflac

you mentioned in ReadMe:
but i can't open these 3 
while i try to download it shows

Not Found

The requested URL /~13akga/content/download.php was not found on this server.

Apache/2.2.22 (Debian) Server at apaczai.elte.hu Port 80

**Comment by jincysam** [comment]
I edited my question..can you give me example in objectiveC

**Comment by H2CO3** [comment]
What example? This library is just C. You can use it directly in exactly the way it's used in the examples which are already provided. If the binary distribution of the dependencies is not available, you will have to compile them from source.
